
;; ORG MODE
(require 'org-install)
(require 'org)
(add-to-list 'auto-mode-alist '("\\.org\\'" . org-mode))
(setq org-directory (expand-file-name "~/Google Drive/org-files/org"))
(setq org-default-notes-file (concat org-directory "/notes.org"))
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)

(setq org-publish-project-alist
      '(
	
	("org-notes"
	 :base-directory "~/Google Drive/org-files/org"
	 :base-extension "org"
	 :index-filename "sitemap.org"
	 :auto-sitemap t                ;autogenerated sitemap
	 :index-title "Sitemap"
	 :publishing-directory "~/Google Drive/org-files/html"
	 :recursive t
	 :publishing-function org-publish-org-to-html
	 :headline-levels 4             ; Just the default for this project.
	 :auto-preamble t
	 )
	
	))
